name: ferry_cache
version: 0.5.5-dev.9
homepage: https://ferrygraphql.com/
description: A normalized, strongly typed, optimistic cache for GraphQL Operations and Fragments
repository: https://github.com/gql-dart/ferry
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ferry_exec:
    path: ../ferry_exec
  meta: ^1.3.0
  rxdart: ^0.27.1
  normalize:
    path: ../normalize
  ferry_store:
    path: ../ferry_store
  collection: ^1.15.0
  pedantic: ^1.11.0
dev_dependencies:
  test: ^1.16.8
  ferry_test_graphql:
    path: ../ferry_test_graphql